### ISSUE TITLE
Office League - Bugs & Improvements - Batch 4

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-office-league#288]
- [x] Admin pictures should be round
- [x] Add admin as players on league creation
- [x] Add players during league creation
- [x] Delete game if admin
